# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/completion.sh

builds:
  - env:
      - CGO_ENABLED=0
    binary: allincart-cli
    ldflags: -s -w -X 'github.com/allincart-org/allincart-cli/cmd.version={{ .Version }}'
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    ignore:
      - goos: linux
        goarch: '386'

archives:
  - id: with-version
    builds: [allincart-cli]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

  - id: no-version
    builds: [allincart-cli]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os | title }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

nfpms:
  - id: default
    formats: [deb, rpm, apk]
    package_name: allincart-cli
    bindir: /usr/bin
    builds: [allincart-cli]
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

release:
  github:
    owner: allincart
    name: allincart-cli

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request:'
  groups:
    - title: 🚀 Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 🧰 Maintenance
      order: 999