# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/completion.sh

builds:
  - env:
      - CGO_ENABLED=0
    binary: allincart-cli
    ldflags: -s -w -X 'github.com/allincart-org/allincart-cli/cmd.version={{ .Version }}'
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    ignore:
      - goos: linux
        goarch: '386'

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - completions/*

release:
  github:
    owner: allincart
    name: allincart-cli

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request:'
  groups:
    - title: 🚀 Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 🧰 Maintenance
      order: 999