# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/completion.sh

builds:
  - env:
      - CGO_ENABLED=0
    binary: allincart-cli
    ldflags: -s -w -X 'github.com/allincart-org/allincart-cli/cmd.version={{ .Version }}'
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    ignore:
      - goos: linux
        goarch: '386'

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - completions/*

release:
  github:
    owner: allincart
    name: allincart-cli

dockers:
  # AMD64
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.4-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.4"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.3-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.3"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.2-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.2"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.1-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.1"
      - "--platform=linux/amd64"

  # ARM64
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.4-arm64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.4"
      - "--platform=linux/arm64"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.3-arm64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.3"
      - "--platform=linux/arm64"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.2-arm64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.2"
      - "--platform=linux/arm64"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.1-arm64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.1"
      - "--platform=linux/arm64"

  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.bin
    image_templates:
      - "allincart-org/allincart-cli:bin-{{ .Tag }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.bin
    image_templates:
      - "allincart-org/allincart-cli:bin-{{ .Tag }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  # Allincart Docker Hub
  - name_template: allincart-org/allincart-cli:latest
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.3-amd64"
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.3-arm64"

  - name_template: allincart-org/allincart-cli:latest-php-8.4
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.4-amd64"
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.4-arm64"

  - name_template: allincart-org/allincart-cli:latest-php-8.3
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.3-amd64"
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.3-arm64"

  - name_template: allincart-org/allincart-cli:latest-php-8.2
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.2-amd64"
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.2-arm64"

  - name_template: allincart-org/allincart-cli:latest-php-8.1
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.1-amd64"
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.1-arm64"

  - name_template: allincart-org/allincart-cli:{{ .Tag }}
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.3-amd64"
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.3-arm64"

  - name_template: allincart-org/allincart-cli:{{ .Tag }}-php-8.3
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.3-amd64"
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.3-arm64"

  - name_template: allincart-org/allincart-cli:{{ .Tag }}-php-8.2
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.2-amd64"
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.2-arm64"

  - name_template: allincart-org/allincart-cli:{{ .Tag }}-php-8.1
    image_templates:
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.1-amd64"
      - "allincart-org/allincart-cli:{{ .Tag }}-php-8.1-arm64"

  - name_template: allincart-org/allincart-cli:bin-{{ .Tag }}
    image_templates:
      - "allincart-org/allincart-cli:bin-{{ .Tag }}-amd64"
      - "allincart-org/allincart-cli:bin-{{ .Tag }}-arm64"

  - name_template: allincart-org/allincart-cli:bin
    image_templates:
      - "allincart-org/allincart-cli:bin-{{ .Tag }}-amd64"
      - "allincart-org/allincart-cli:bin-{{ .Tag }}-arm64"

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: checksum
    args:
    - "sign-blob"
    - "--output-certificate=${certificate}"
    - "--output-signature=${signature}"
    - '${artifact}'
    - "--yes"

docker_signs:
  - cmd: cosign
    env:
    - COSIGN_EXPERIMENTAL=1
    artifacts: all
    args:
    - 'sign'
    - '${artifact}'
    - "--yes"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request:'
  groups:
    - title: 🚀 Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 🧰 Maintenance
      order: 999

aurs:
  - homepage: https://developer.allincart.net/
    description: A cli which contains handy helpful commands for daily Allincart tasks
    license: MIT
    maintainers:
      - "Soner Sayakci <s.sayakci@allincart.net>"
      - "Max <max@swk-web.com>"
    private_key: '{{ .Env.AUR_KEY }}'
    commit_author:
      name: "Allincart Bot"
      email: github@allincart.net
    git_url: 'ssh://aur@aur.archlinux.org/allincart-cli-bin.git'
    depends:
      - "git"
    package: |-
      install -Dm755 "./allincart-cli" "${pkgdir}/usr/bin/allincart-cli"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/allincart-cli/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/allincart-cli.bash" "${pkgdir}/usr/share/bash-completion/completions/allincart-cli"
      install -Dm644 "./completions/allincart-cli.zsh" "${pkgdir}/usr/share/zsh/site-functions/_allincart-cli"
      install -Dm644 "./completions/allincart-cli.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/allincart-cli.fish"

nix:
  - name: allincart-cli
    repository:
      owner: FriendsOfAllincart
      name: nur-packages
      branch: main
      token: "{{ .Env.NUR_GITHUB_TOKEN }}"
    commit_author:
      name: "Allincart Bot"
      email: github@allincart.net
    post_install: |
      installShellCompletion --cmd allincart-cli \
      --bash <($out/bin/allincart-cli completion bash) \
      --zsh <($out/bin/allincart-cli completion zsh) \
      --fish <($out/bin/allincart-cli completion fish)
    homepage: "https://sw-cli.fos.gg"
    description: "Command line tool for Allincart 6"
    license: "mit"

nfpms:
  -
    package_name: allincart-cli
    vendor: "allincart AG"
    homepage: https://github.com/allincart-org/allincart-cli/
    maintainer: Soner Sayakci <s.sayakci@allincart.net>
    description: A cli which contains handy helpful commands for daily Allincart tasks
    license: MIT
    contents:
      - src: ./completions/allincart-cli.bash
        dst: /etc/bash_completion.d/allincart-cli
      - src: ./completions/allincart-cli.fish
        dst: /usr/share/fish/completions/allincart-cli.fish
      - src: ./completions/allincart-cli.zsh
        dst: /usr/local/share/zsh/site-functions/_allincart-cli
    formats:
      - apk
      - deb
      - rpm

brews:
  - repository:
      owner: FriendsOfAllincart
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Frosh Automation
      email: ci@fos.gg
    goarm: "7"
    homepage: https://friendsofallincart.net
    description: Allincart CLI helps Allincart developers manage extensions
    license: MIT
    directory: Formula
    test: |
      system "#{bin}/allincart-cli --version"
    dependencies:
    - name: node-sass
    - name: git
      type: optional
    - name: node
      type: optional
    install: |-
      bin.install "allincart-cli"
      bash_completion.install "completions/allincart-cli.bash" => "_allincart-cli"
      zsh_completion.install "completions/allincart-cli.zsh" => "_allincart-cli"
      fish_completion.install "completions/allincart-cli.fish"
  - repository:
      owner: allincart
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN_ALLINCART }}"
    commit_author:
      name: Frosh Automation
      email: ci@fos.gg
    goarm: "7"
    homepage: https://allincart.net
    description: Allincart CLI helps Allincart developers manage extensions
    license: MIT
    directory: Formula
    test: |
      system "#{bin}/allincart-cli --version"
    dependencies:
    - name: node-sass
    - name: git
      type: optional
    - name: node
      type: optional
    install: |-
      bin.install "allincart-cli"
      bash_completion.install "completions/allincart-cli.bash" => "_allincart-cli"
      zsh_completion.install "completions/allincart-cli.zsh" => "_allincart-cli"
      fish_completion.install "completions/allincart-cli.fish"

npms:
  - name: "@allincart-ag/allincart-cli"
    description: "Allincart CLI helps Allincart developers manage extensions"
    license: MIT
    homepage: https://developer.allincart.net/docs/products/cli/
    keywords:
      - cli
      - allincart
    repository: https://github.com/allincart-org/allincart-cli
    bugs: https://github.com/allincart-org/allincart-cli/issues
    access: public

    