name: Smoke Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # ratchet:actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
          check-latest: true

      - name: Setup PHP
        uses: shivammathur/setup-php@0f7f1d08e3e32076e51cae65eb0b0c871405b16e # ratchet:shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Compile allincart-cli
        run: go build

      - name: Checkout Plugin
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          repository: 'allincart-org/SwagPlatformDemoData'
          ref: '2667c84cb9e592f943a1f310cbd6f8b3bcb1e994'
          path: 'plugin'

      - name: Create Allincart
        run: ./allincart-cli project create allincart 6.7.0.0

      - name: Build asset of Plugin
        run: ./allincart-cli extension zip plugin

      - name: Build asset of Plugin without Git
        run: ./allincart-cli extension zip plugin --disable-git --release

      - name: Validate Plugin
        run: ./allincart-cli extension validate SwagPlatformDemoData.zip

      - name: Get Changelog
        run: ./allincart-cli extension get-changelog SwagPlatformDemoData.zip

      - name: Build asset against custom PROJECT_ROOT
        env:
          ALLINCART_PROJECT_ROOT: ${{ github.workspace }}/allincart
        run: |
          mv plugin/.allincart-extension.yml plugin/.allincart-extension-disable.yml
          ./allincart-cli extension build plugin
          mv plugin/.allincart-extension-disable.yml plugin/.allincart-extension.yml

      - name: Setup the project
        run: ./allincart-cli project ci allincart
